Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,24 +17,21 @@ jobs:
         id: deployEnv
         run: |
           deploy_environments=[]
-          is_develop_branch="${{ github.ref }} == refs/heads/develop"
-          is_production_branch="${{ github.ref }} == refs/heads/main"
-          is_production_synced_with_develop="-z `git cherry origin/main origin/develop`"
+          is_develop_branch=$([[ "${{ github.ref }}" == refs/heads/develop ]] && echo true || echo false)
+          is_production_branch=$([[ "${{ github.ref }}" == refs/heads/production ]] && echo true || echo false)
+          is_production_synced_with_develop=$(git cherry origin/production origin/develop)
 
           echo "Is develop: ${is_develop_branch}"
           echo "Is prod: ${is_production_branch}"
           echo "Is synced: ${is_production_synced_with_develop}"
           
           deploy_environments=""
-          if [[ ${is_develop_branch} ]]; then
+          if [[ $is_develop == true ]]; then
             deploy_environments="staging"
-          elif [[ ${is_production_branch} ]]; then
-            if [[ ${is_production_synced_with_develop} ]]; then
-              echo "::error::Cannot deploy out of sync production branch to production environments: ${{ inputs.production_environments }}"
-              exit 1
-            else
-              deploy_environments="${{ inputs.production_environments }}"
-            fi
+          elif [[ $is_prod == true ]] && [[ -n $changes ]]; then
+            deploy_environments="${{ inputs.production_environments }}"
+          elif [[ $is_prod == true ]] && [[ -z $changes ]]; then
+            echo "::error::Cannot deploy out of sync production branch to production environments: ${{ inputs.production_environments }}"
           fi
           echo "deploy_environments=[${deploy_environments}]" >> $GITHUB_OUTPUT
           echo "${deploy_environments}"
